import type { NarrativeBlock } from "@/components/NarrativeCaseStudyPage";

// English website edition. The Chinese factual master remains unchanged in case-study.md.
export const caseStudyTitle = "Improving Text Input and Expression in Digital Products";
export const caseStudyBlocks = [
  { type: "heading", level: 1, text: caseStudyTitle },
  { type: "quote", text: "The Lincoln Way: how I turned ‘how many characters should we allow?’ into a mobile text system that is explainable, recoverable, and ready for delivery." },
  { type: "heading", level: 2, text: "01｜Project context: using a small detail to test the judgment of an entire product" },
  { type: "paragraph", text: "The Lincoln Way is a mobile app that gives Lincoln owners access to vehicle status, community participation, related purchases, and official services. Over a project period of roughly one month, I worked as the agency-side UX designer through design and launch, responsible for requirement analysis, competitive research, character-limit rules, interaction design, and design specifications. Client-side designers and product managers reviewed and approved the proposal." },
  { type: "paragraph", text: "The project initially looked like a question of how many characters an input should allow. But once name, nickname, vehicle identification number (VIN), and post body were considered together, the numbers became only the surface. The four fields support identity records, public presentation, system identification, and open expression. What needed consistency was not the appearance of a counter, but the team's method for judging different text tasks." },
  { type: "heading", level: 2, text: "02｜Outcome preview: from four parameters to one rule system" },
  { type: "paragraph", text: "I did not ultimately deliver a component sheet that showed a character count on every input. Instead, I developed a rule framework that begins with field semantics and applied it to four representative scenarios:" },
  { type: "list", ordered: false, items: [
    "**Identity record:** A name field needs to explain valid formats rather than merely telling the user they are wrong.",
    "**Public identity:** A nickname has to handle a 14-character limit, permitted characters, and immediate recovery together.",
    "**Exact identification:** A VIN has one fixed 17-character answer; accurate entry, scanning, and findability matter more than continuous counting.",
    "**Content expression:** A post body has a boundary of 1,000 and needs to connect approaching the limit, exceeding it, publishing state, and topic allowance into one feedback model.",
  ] },
  { type: "paragraph", text: "The work covered requirement analysis, competitive research, rule definition, interaction design, and design specifications, and proceeded through review and launch with the project. It converted scattered field parameters into decisions the team could discuss and accept: **why the limit exists, when users need to know about it, and how they can continue after an error.**" },
  { type: "heading", level: 2, text: "03｜Problem evidence: the same ‘character limit’ created four different risks" },
  { type: "table", headers: ["Scenario", "Launched behavior", "Key risk I identified", "Design priority"], rows: [
    ["Name", "English input triggers ‘Please enter valid text,’ without explaining acceptable formats", "The user knows the attempt failed, but not which rule was broken or how to fix it", "Explain the rule and the path to recovery"],
    ["Nickname", "Chinese and English both count toward 14; special characters other than underscore are not allowed; errors appear in real time", "Length and legal-character rules operate together, so a generic message increases trial and error", "Specific, local, immediate feedback"],
    ["VIN", "Fixed at 17 characters; no count in the empty state; manual entry, scanning, and find-help are available", "One wrong character prevents vehicle binding, while a permanent counter may not reduce the primary cost", "Accurate entry and alternative paths"],
    ["Post body", "Displays `X/1000`; entry can continue at `1009/1000`, without a clear invalid state", "The number is visible, but publishability and recovery remain unclear", "Close the loop between state, consequence, and recovery"],
  ] },
  { type: "paragraph", text: "The detail that most clearly exposed the system problem appeared at `997/1000`: the page still showed three units remaining, but adding a suggested topic produced a message saying the input had reached its limit. This was not simply a counter that failed to turn red. The body and topic may share an unexplained allowance, while the page presents two conflicting models of remaining capacity. Without engineering-rule evidence, I recorded this as an **allowance coupling that needs confirmation**, rather than declaring it a software defect." },
  { type: "heading", level: 2, text: "04｜Cross-diagnosis: input rules have to pass through four perspectives" },
  { type: "paragraph", text: "Instead of continuing to collect competitors' numbers, I re-examined each field through four perspectives:" },
  { type: "table", headers: ["Diagnostic perspective", "Question to answer", "Design details it affects"], rows: [
    ["User mental model", "Does the user know the correct answer? What does ‘one character’ mean to them?", "Whether to explain in advance, whether to say ‘character’ or another unit, and whether the error is understandable"],
    ["Content responsibility", "Is the content a real identity, public expression, machine identifier, or free-form creation?", "Strength of the limit, allowed characters, and whether continued input is permitted"],
    ["Task risk", "Will an error merely affect presentation, or directly block binding and submission?", "Feedback timing, scan/help access, and submission state"],
    ["System chain", "Do front-end counting, API validation, the database, and final display use the same rule?", "Boundary cases, front-end/back-end consistency, and acceptance criteria"],
  ] },
  { type: "paragraph", text: "This diagnosis moved the discussion from ‘what limit do competitors usually use?’ to ‘why does this field need this rule?’ The framework and interaction proposal entered delivery after review and approval by client-side designers and product managers. The available material establishes review and launch, but does not support a more specific claim that a particular discussion changed a particular stakeholder's opinion." },
  { type: "heading", level: 2, text: "05｜Three key decisions: turning details into a system" },
  { type: "heading", level: 3, text: "Decision 1: standardize the sequence of judgment, not the counter" },
  { type: "paragraph", text: "I classified fields by answer certainty × rule complexity × error cost × downstream display, and then decided whether to provide guidance, when to give feedback, and how to validate." },
  { type: "table", headers: ["Field type", "Rule strategy", "Why it should not use the same interaction"], rows: [
    ["Name / identity record", "When a rule is triggered, explain locally what is not accepted and how to fix it", "‘Please enter valid content’ exposes the system's judgment without helping the user complete identity entry"],
    ["Nickname / public identity", "Explain the 14-character and permitted-character rules in advance; provide immediate feedback during entry", "Users actively create nicknames, so knowing the boundary early reduces repeated guessing"],
    ["VIN / fixed identifier", "Do not make a persistent count the default; emphasize the 17-character target, scanning, and find-help", "The user is not creating content, but locating and accurately transcribing one unique answer"],
    ["Body / open expression", "Provide continuous progress; progressively strengthen feedback near the limit, beyond it, and at publication", "Long-form content needs adjustment during writing without discarding the expression the moment the boundary is crossed"],
  ] },
  { type: "paragraph", text: "The smallest detail that best demonstrates judgment here is that **not showing a count can itself be an intentional design decision**. The VIN screen gives space to camera scanning, help content, and confirmation states because those paths address the user's likely failure more directly than `0/17`." },
  { type: "heading", level: 3, text: "Decision 2: describe the counting unit in product language users understand" },
  { type: "paragraph", text: "Bytes, encoding units, and a user's perception of ‘one character’ are not the same thing. In the launched behavior, Chinese characters, Latin letters, and numbers each count as one, while observed emoji count as two. Without source code or technical documentation, I do not attribute the emoji behavior to a specific underlying implementation." },
  { type: "paragraph", text: "At the specification level, three things must be explicit: which term the interface uses to describe the limit; how Chinese characters, Latin letters, numbers, spaces, line breaks, combining characters, and emoji are counted; and whether front-end display, API validation, and server-side storage use the same definition. For users, seeing both Chinese and English count as one better matches the intuition of entering one visible symbol. For the team, boundary cases must turn that intuition into a testable definition." },
  { type: "paragraph", text: "This choice has a cost: counting by user-perceived units makes engineering and testing more complex than using a simple string length. But if a rule is convenient for development while users see one Chinese character counted as two, the cost has merely been transferred from implementation to confusion and failure." },
  { type: "heading", level: 3, text: "Decision 3: make exceeding the limit a recoverable state, not a single error" },
  { type: "paragraph", text: "For long text, I prefer to let users continue typing and preserve their context. But exceeding the limit must simultaneously change the count treatment, publishing availability, and supporting explanation, while stating how much is over, which content is affected, and how to recover. This protects the content; it does not tolerate an unexplained invalid state." },
  { type: "paragraph", text: "I divided long-text feedback into four stages:" },
  { type: "list", ordered: true, items: [
    "**Normal entry:** The count remains low-emphasis so the user can focus on expression.",
    "**Approaching the limit:** Feedback becomes stronger, giving the user time to edit.",
    "**Over the limit:** The excess and unavailable publish state become explicit, while the full text remains editable.",
    "**Return to valid:** Once the user edits back into range, the publish action and visual feedback recover immediately.",
  ] },
  { type: "paragraph", text: "The `997/1000` topic case also requires the error to identify the true object. If a topic consumes the body allowance, that relationship should be explained before selection and reflected in one count. If the allowances are independent, a topic failure should not be described as ‘input content has reached the limit.’ Compared with a generic toast, a local message such as ‘Body and topic together exceed the limit; shorten the body or remove the topic’ preserves context and a recovery path." },
  { type: "heading", level: 2, text: "06｜System extension: I documented a decision tool, not a table of standard numbers" },
  { type: "paragraph", text: "During the research, I organized common patterns into a selection table that can support future field reviews:" },
  { type: "table", headers: ["Design question", "Suitable strategy", "When not to apply it mechanically"], rows: [
    ["Should the limit be disclosed in advance?", "Explain it early for short fields with complex rules; make the boundary discoverable for long text", "When the answer is unique and find-help matters more, a count does not need to dominate attention"],
    ["Should a count be continuously visible?", "Show it continuously or near the threshold for long text that users actively regulate", "For very short fixed codes, completion and format feedback are usually more important"],
    ["Can entry continue after the limit?", "For authored content, retain excess text but prevent submission so editing can recover it", "For fixed per-character inputs such as security codes, direct restriction may be appropriate, but the target format still needs explanation"],
    ["Where should the error appear?", "Prefer local feedback for field-specific issues; explain linked objects for cross-field or shared-allowance issues", "Do not rely only on a toast for an error that requires sustained editing; once it disappears, the user loses the basis for recovery"],
    ["How should multiline input expand?", "Fixed scrolling preserves page structure; auto-grow supports review; focus mode supports extended creation", "Do not choose one expansion model without considering the importance of the content and the page structure"],
  ] },
  { type: "paragraph", text: "The value of this table is not to make every input look the same. It enables design, product, front-end, back-end, and QA to align around the same questions: the object being limited, counting definition, feedback timing, submission conditions, display capacity, and boundary cases." },
  { type: "heading", level: 2, text: "07｜System in context: four pages, four detailed judgments" },
  { type: "heading", level: 3, text: "Profile: translating ‘invalid format’ into a recovery action" },
  { type: "paragraph", text: "Name and nickname appear on the same page, but should not share one vague error. A name is an identity record and needs a clear acceptable format. A nickname is public-facing and should turn its 14-character boundary and special-character rules into guidance the user can act on. The design goal is not to make every error red, but to tell users **what is wrong, why, and what to change next**." },
  { type: "image", alt: "Launched profile page", src: "profile-overview.png" },
  { type: "image", alt: "Real-time nickname rule feedback", src: "profile-nickname-invalid.png" },
  { type: "heading", level: 3, text: "Add vehicle: returning fixed length to the real task" },
  { type: "paragraph", text: "A 17-character VIN is not an ordinary character limit; it is a required identifier for binding a vehicle. The page provides keyboard entry, camera scanning, and help for finding the VIN, showing that the design object should be the full entry task. Once bound, users can access vehicle status, financing, vehicle warnings, appointments, and other services. Accurate first-time entry therefore deserves priority over a continuously visible counter." },
  { type: "image", alt: "Vehicle identification number entry", src: "vin-entry.png" },
  { type: "image", alt: "Vehicle binding entry point and subsequent value", src: "vehicle-empty.png" },
  { type: "heading", level: 3, text: "Publishing: aligning the visible number with the real usable allowance" },
  { type: "paragraph", text: "The body counter `X/1000` provides progress without fully expressing state. At `1009/1000`, entry continues but the counter does not clearly escalate. At `997/1000`, adding a topic produces a limit message. Together, these screens show that counting, topic rules, publishing state, and error copy must be designed as one interaction chain rather than four independent controls." },
  { type: "image", alt: "Post body beyond the limit without a clear state", src: "post-overflow.png" },
  { type: "image", alt: "Adding a topic triggers an allowance message", src: "post-topic-limit.png" },
  { type: "paragraph", text: "These screenshots show the launched version. Over-limit color, explanation of shared body/topic allowance, emoji counting boundaries, and alternative states remain `Portfolio reconstruction / further exploration`. When developed, they will be presented separately from launched facts." },
  { type: "heading", level: 2, text: "08｜Validation and measurement: limited analytics access does not make outcomes a blank space" },
  { type: "paragraph", text: "Three levels of outcome can currently be confirmed: I completed the stated work from research through specification; client-side designers and product managers reviewed and approved the proposal; and the related experience participated in launch. As an external design partner, I could not continuously access analytics after delivery, so I do not claim a specific improvement in submission success, completion time, or business conversion." },
  { type: "paragraph", text: "If validation continued, I would measure each task rather than cover every field with one aggregate metric:" },
  { type: "table", headers: ["Scenario", "Core metrics", "Judgment being tested"], rows: [
    ["Name / nickname", "Rule-error rate, first-save success, repeated instances of the same error", "Whether guidance makes the rule predictable and recoverable"],
    ["VIN", "First-entry success, average completion time, scan adoption, 17-character validation failure rate", "Whether help and scanning are more effective than persistent counting"],
    ["Post body", "Over-limit incidence, recovery rate, recovery time, abandonment after exceeding the limit", "Whether continued entry and recovery feedback protect expression"],
    ["Body + topic", "Accuracy identifying the allowance error, topic-add failure rate", "Whether users understand what is actually being limited"],
  ] },
  { type: "paragraph", text: "Without live analytics, task testing could still begin: ask participants to edit a nickname, manually enter or scan a VIN, revise a 1,020-unit post until it can be published, and explain whether a topic counts toward the 1,000. Recording first-attempt success, recovery paths, and how participants restate the rule would test whether the design explanation works." },
  { type: "heading", level: 2, text: "09｜My contribution: mid-to-senior capability means completing the judgment, not multiplying details" },
  { type: "list", ordered: false, items: [
    "**Diagnosis:** Identified the shared problem among field semantics, user mental models, and system validation across four separate inputs.",
    "**Definition:** Advanced ‘how many characters?’ into the object being limited, counting definition, feedback timing, submission conditions, and boundary testing.",
    "**Detail:** Distinguished name from nickname, count from state, body allowance from topic allowance, and ‘allowed to keep typing’ from ‘allowed to publish.’",
    "**Collaborative delivery:** Turned research into interactions and specifications that client-side designers, product managers, engineering, and QA could review and execute.",
  ] },
  { type: "paragraph", text: "This project is not evidence of how many prompts I added to each field. It demonstrates whether I can see user understanding, content responsibility, engineering consistency, and a validation loop inside a very small interface detail." },
  { type: "heading", level: 2, text: "10｜Reflection" },
  { type: "paragraph", text: "If I were to run the project again, I would deliver field rules together with analytics and test cases earlier, and preserve why each choice was made rather than only the final parameter. Even if an external team cannot access long-term data, the work could then answer before launch whether a limit is too strict, whether users understand it, whether an error identifies the right object, and whether front end and back end use the same counting definition." },
  { type: "paragraph", text: "The problem I ultimately addressed was not where to place the counter, but **how to make product boundaries understandable to users, executable by teams, and recoverable when something goes wrong.**" },
] satisfies NarrativeBlock[];
