import Link from "next/link";
import { ArrowLeft, ArrowRight, CircleAlert } from "lucide-react";
import AgentDimensionLab from "./AgentDimensionLab";
import ExpandableResearchImage from "./ExpandableResearchImage";
import { autonomousAgentCaseStudy as project, autonomousAgentSourceCoverage } from "@content/projects/autonomous-driving-to-agent/case-study.zh";

const assetRoot = "/assets/images/autonomous-driving-to-agent";

function SourceSection({ sourceIds, className = "", children }: { sourceIds: readonly string[]; className?: string; children: React.ReactNode }) {
  return <section data-source-ids={sourceIds.join(" ")} className={className}>{children}</section>;
}

export default function AutonomousAgentResearchPage() {
  void autonomousAgentSourceCoverage;
  return <main className="case-study-page min-h-screen bg-workspace-bg text-workspace-text">
    <header className="sticky top-0 z-30 border-b border-workspace-border bg-workspace-bg/95 backdrop-blur-sm"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-3 sm:px-8"><Link href="/zh" className="inline-flex min-h-11 items-center gap-2 rounded-lg px-3 font-mono text-xs font-bold hover:bg-white focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-workspace-accent"><ArrowLeft className="h-4 w-4" aria-hidden="true" />返回 Workspace</Link><span className="font-mono text-[10px] font-bold uppercase tracking-[0.14em] text-neutral-500">Independent research · 2026</span></div></header>

    <article>
      <SourceSection sourceIds={project.thesis.sourceIds} className="mx-auto max-w-7xl px-5 pb-24 pt-12 sm:px-8 sm:pb-32 sm:pt-20">
        <h1 className="case-study-title !max-w-5xl">{project.title}</h1>
        <p className="mt-8 max-w-[66ch] text-lg leading-8 text-neutral-600 sm:text-xl sm:leading-9">{project.dek}</p>
        <p className="mt-3 max-w-[66ch] text-xl font-bold leading-8 text-neutral-900 sm:text-2xl">{project.thesis.proposition}</p>
        <h2 className="mt-12 text-2xl font-black tracking-tight text-neutral-950 sm:text-4xl">{project.thesis.title}</h2>
        <div className="mt-5 max-w-[72ch] space-y-5">{project.thesis.paragraphs.map((paragraph) => <p key={paragraph} className="text-base leading-8 text-neutral-700 sm:text-lg">{paragraph}</p>)}</div>
        <div className="mt-10 grid gap-3 sm:grid-cols-2">{project.thesis.questions.map((question, index) => <div key={question} className="flex gap-3 rounded-xl bg-white p-4 text-sm leading-6 text-neutral-700"><span className="font-mono text-xs font-bold text-workspace-accent">{String(index + 1).padStart(2, "0")}</span>{question}</div>)}</div>
        <p className="mt-10 max-w-[72ch] text-base leading-8 text-neutral-700 sm:text-lg">{project.thesis.drivingReference}</p>
        <p className="mt-7 max-w-[76ch] text-xs leading-6 text-neutral-500"><strong>研究边界：</strong>{project.boundary}</p>
      </SourceSection>

      <SourceSection sourceIds={project.agentLoop.sourceIds} className="bg-white py-24 sm:py-32"><div className="mx-auto max-w-7xl space-y-10 px-5 sm:px-8"><div className="max-w-4xl space-y-5"><h2 className="case-study-section-title">{project.agentLoop.title}</h2><p className="max-w-[68ch] text-base leading-8 text-neutral-600 sm:text-lg">{project.agentLoop.paragraphs[0]}</p><div className="flex flex-wrap items-center gap-2" aria-label="Agent 基本闭环">{project.agentLoop.agentFlow.map((step, index) => <div key={step} className="contents"><span className="rounded-lg bg-[#e9f4fb] px-3 py-2 font-mono text-xs font-bold text-[#18384f]">{step}</span>{index < project.agentLoop.agentFlow.length - 1 ? <ArrowRight className="h-4 w-4 text-neutral-400" aria-hidden="true" /> : null}</div>)}</div><p className="max-w-[68ch] text-base leading-8 text-neutral-600 sm:text-lg">{project.agentLoop.paragraphs[1]}</p><div className="flex flex-wrap items-center gap-2" aria-label="自动驾驶系统闭环">{project.agentLoop.drivingFlow.map((step, index) => <div key={step} className="contents"><span className="rounded-lg bg-[#f1eee8] px-3 py-2 text-xs font-semibold text-neutral-700">{step}</span>{index < project.agentLoop.drivingFlow.length - 1 ? <ArrowRight className="h-4 w-4 text-neutral-400" aria-hidden="true" /> : null}</div>)}</div></div><ExpandableResearchImage src={`${assetRoot}/${project.agentLoop.media.src}`} alt={project.agentLoop.media.alt} width={project.agentLoop.media.width} height={project.agentLoop.media.height} priority caption="研究信息图：完整闭环、现实世界交互与高风险约束共同构成类比基础。" /></div></SourceSection>

      <SourceSection sourceIds={project.riskReference.sourceIds} className="mx-auto max-w-7xl px-5 py-24 sm:px-8 sm:py-32"><div className="max-w-4xl"><h2 className="case-study-section-title">{project.riskReference.title}</h2><p className="mt-5 max-w-[68ch] text-base leading-8 text-neutral-600 sm:text-lg">{project.riskReference.summary}</p></div><div className="mt-10 overflow-hidden rounded-2xl bg-white"><div className="hidden grid-cols-[9rem_1fr_1.25fr] bg-[#0e1820] px-6 py-4 text-xs font-bold text-white sm:grid"><span>维度</span><span>一般数字 Agent</span><span>自动驾驶带来的要求</span></div>{project.riskReference.rows.map(([dimension, digital, driving]) => <div key={dimension} className="grid gap-2 border-b border-neutral-100 p-5 last:border-0 sm:grid-cols-[9rem_1fr_1.25fr] sm:gap-6 sm:px-6"><strong className="text-sm text-neutral-900">{dimension}</strong><p className="text-sm leading-6 text-neutral-500">{digital}</p><p className="text-sm leading-6 text-neutral-800">{driving}</p></div>)}</div><p className="mt-8 max-w-[72ch] text-base leading-8 text-neutral-700">{project.riskReference.closing}</p></SourceSection>

      <SourceSection sourceIds={project.control.sourceIds} className="bg-[#0e1820] py-20 text-white sm:py-24"><div className="mx-auto max-w-7xl px-5 sm:px-8"><div className="max-w-4xl space-y-4"><h2 className="case-study-section-title !text-white">{project.control.title}</h2><p className="max-w-[68ch] text-base leading-8 text-slate-200 sm:text-lg">{project.control.intro}</p><p className="max-w-[68ch] text-base leading-8 text-slate-200 sm:text-lg">{project.control.summary}</p></div><div className="mt-8 overflow-hidden rounded-2xl bg-white/10"><div className="grid grid-cols-[3rem_1.25fr_1fr_1fr] gap-2 bg-[#111f29] px-4 py-3 text-[10px] font-bold text-slate-400 sm:grid-cols-[4rem_1.35fr_1fr_1.1fr] sm:px-5 sm:text-xs"><span>阶段</span><span>控制主体</span><span>用户角色</span><span>体验命题</span></div>{project.control.levels.map((item) => <article key={item.level} className={`grid grid-cols-[3rem_1.25fr_1fr_1fr] items-center gap-2 border-t border-white/10 px-4 py-4 sm:grid-cols-[4rem_1.35fr_1fr_1.1fr] sm:px-5 ${item.level === "L3" ? "bg-[#2e94e3]" : "bg-[#172631]"}`}><strong className="text-xl tracking-[-0.03em] sm:text-2xl">{item.level}</strong><p className="text-xs font-bold leading-5 sm:text-sm">{item.control}</p><p className="text-xs leading-5 text-slate-200 sm:text-sm">{item.role}</p><p className="text-[11px] leading-5 text-slate-300 sm:text-xs">{item.experience}</p></article>)}</div><p className="mt-7 max-w-[72ch] text-base leading-8 text-slate-200">{project.control.analogy}</p></div></SourceSection>

      <SourceSection sourceIds={project.dimensionsIntro.sourceIds} className="bg-white py-20 sm:py-24"><div className="mx-auto max-w-7xl space-y-10 px-5 sm:px-8"><div className="max-w-4xl"><p className="max-w-[72ch] text-lg font-medium leading-9 text-neutral-800">{project.dimensionsIntro.bridge}</p><h2 className="case-study-section-title mt-12">{project.dimensionsIntro.title}</h2><p className="mt-5 max-w-[68ch] text-base leading-8 text-neutral-600 sm:text-lg">{project.dimensionsIntro.summary}</p></div><ExpandableResearchImage src={`${assetRoot}/${project.dimensionsIntro.media.src}`} alt={project.dimensionsIntro.media.alt} width={project.dimensionsIntro.media.width} height={project.dimensionsIntro.media.height} caption="五个维度不是线性步骤，而是共同约束系统行为的设计框架。" /></div></SourceSection>

      <div className="mx-auto max-w-7xl space-y-28 px-5 py-24 sm:space-y-40 sm:px-8 sm:py-32">{project.dimensions.map((dimension, index) => <section key={dimension.id} className="scroll-mt-24"><div className="max-w-4xl"><div className="flex items-baseline gap-4"><span className="font-mono text-xs font-bold text-workspace-accent">{String(index + 1).padStart(2, "0")}</span><h2 className="case-study-section-title">{dimension.title}</h2></div><p className="mt-2 font-mono text-xs font-bold text-neutral-400">{dimension.english}</p><p className="mt-5 max-w-[68ch] text-base leading-8 text-neutral-600 sm:text-lg">{dimension.summary}</p></div><div className={`mt-10 grid gap-8 xl:grid-cols-[minmax(0,1.45fr)_minmax(22rem,0.55fr)] xl:items-start ${index % 2 === 1 ? "xl:[&>figure]:order-2" : ""}`}><ExpandableResearchImage src={`${assetRoot}/${dimension.image}`} alt={dimension.alt} width={3172} height={1984} caption={dimension.caption} /><aside aria-label={dimension.interactionTitle} className="xl:sticky xl:top-24"><div className="mb-3 flex items-center gap-2"><ArrowRight className="h-4 w-4 text-workspace-accent" aria-hidden="true" /><h3 className="case-study-subsection-title">{dimension.interactionTitle}</h3></div><AgentDimensionLab id={dimension.id} /></aside></div></section>)}</div>

      <SourceSection sourceIds={project.principles.sourceIds} className="bg-[#dcefff] py-24 sm:py-32"><div className="mx-auto max-w-7xl px-5 sm:px-8"><h2 className="case-study-section-title">{project.principles.title}</h2><div className="mt-12 grid gap-px overflow-hidden rounded-2xl bg-[#bdd8eb] md:grid-cols-2">{project.principles.groups.map(([title, body]) => <article key={title} className="bg-[#edf7ff] p-6 sm:p-8"><h3 className="case-study-subsection-title">{title}</h3><p className="mt-4 text-sm leading-7 text-neutral-700">{body}</p></article>)}</div></div></SourceSection>

      <SourceSection sourceIds={project.conclusion.sourceIds} className="bg-[#0e1820] py-24 text-white sm:py-32"><div className="mx-auto grid max-w-7xl gap-12 px-5 sm:px-8 lg:grid-cols-[1fr_0.75fr]"><div><h2 className="case-study-section-title !text-white">{project.conclusion.title}</h2><div className="mt-7 max-w-[68ch] space-y-4">{project.conclusion.paragraphs.map((paragraph) => <p key={paragraph} className="text-base leading-8 text-slate-200">{paragraph}</p>)}</div><blockquote className="mt-8 max-w-[64ch] text-2xl font-medium leading-8 text-white">{project.conclusion.quote}</blockquote></div><div><h3 className="text-lg font-bold !text-white">仍待验证</h3><ul className="mt-5 space-y-4">{project.conclusion.open.map((item) => <li key={item} className="flex gap-3 text-sm leading-6 text-slate-200"><CircleAlert className="mt-1 h-4 w-4 shrink-0 text-[#78c8ff]" aria-hidden="true" />{item}</li>)}</ul></div></div></SourceSection>
    </article>
  </main>;
}
