import Link from "next/link";
import { ArrowLeft, Check, CircleAlert } from "lucide-react";
import ResponsiveProjectImage from "@/components/ResponsiveProjectImage";
import LanguageSwitcher from "@/components/LanguageSwitcher";
import { getDictionary, type Locale } from "@/i18n/dictionary";
import { portfolioCaseStudy as portfolioEn, portfolioContentBalance as enBalance, portfolioSourceCoverage as enCoverage, type PortfolioMedia as EnMedia } from "@content/projects/portfolio-operating-system/case-study.en";
import { portfolioCaseStudy as portfolioZh, portfolioContentBalance as zhBalance, portfolioSourceCoverage as zhCoverage, type PortfolioMedia as ZhMedia } from "@content/projects/portfolio-operating-system/case-study.zh";

type PortfolioProject = typeof portfolioEn | typeof portfolioZh;
type PortfolioMedia = EnMedia | ZhMedia;
type MindmapNode = NonNullable<PortfolioProject["actThree"]["operatingSystem"]["mindmap"]>;
const assetRoot = "/assets/images/portfolio-operating-system";

const labels = {
  en: { nav: ["Generation", "Maintenance", "System"], role: "Role", duration: "Timeline", type: "Type", decision: "Decision", boundary: "Evidence boundary", open: "Still open", results: "Outcome and evidence status", systemMap: "Portfolio Operating System layers" },
  zh: { nav: ["生成", "维护", "系统"], role: "我的职责", duration: "项目周期", type: "项目类型", decision: "设计决策", boundary: "证据边界", open: "仍待解决", results: "成果与证据状态", systemMap: "Portfolio Operating System 分层结构" },
} as const;

const mindmapTranslations: Record<string, string> = {
  "体验层": "Experience layer", "空间化 Workspace": "Spatial Workspace", "窗口与动效": "Windows & motion", "常规项目路径": "Conventional project path",
  "内容层": "Content layer", "全局内容": "Global content", "治理层": "Governance layer", "迁移计划": "Migration plans", "审计": "Audits",
};

function displayNodeLabel(label: string, locale: Locale) { return locale === "en" ? mindmapTranslations[label] ?? label : label; }
function SourceSection({ id, sourceIds, className = "", children }: { id: string; sourceIds: readonly string[]; className?: string; children: React.ReactNode }) { return <section id={id} data-source-ids={sourceIds.join(" ")} className={`scroll-mt-24 ${className}`}>{children}</section>; }

function SectionHeading({ title, summary, inverse = false, protectedPhrase }: { title: string; summary: string; inverse?: boolean; protectedPhrase?: string }) {
  const phraseStart = protectedPhrase ? title.indexOf(protectedPhrase) : -1;
  return <div className="max-w-5xl space-y-4"><h2 className={`case-study-section-title text-balance ${inverse ? "!text-white" : "text-neutral-800"}`}>{phraseStart >= 0 ? <>{title.slice(0, phraseStart)}<span className="whitespace-nowrap">{protectedPhrase}</span>{title.slice(phraseStart + protectedPhrase!.length)}</> : title}</h2><p className={`max-w-[68ch] text-base leading-8 sm:text-lg ${inverse ? "text-slate-200" : "text-neutral-600"}`}>{summary}</p></div>;
}

function Figure({ media, priority = false, compact = false, aligned = false }: { media: PortfolioMedia; priority?: boolean; compact?: boolean; aligned?: boolean }) {
  return <figure data-source-ids={media.sourceIds.join(" ")} className={`min-w-0 ${compact ? "w-full max-w-[13rem] justify-self-center sm:max-w-none" : ""}`}><div className={`overflow-hidden rounded-2xl bg-white shadow-[0_26px_70px_-42px_rgba(24,45,61,0.58)] ${aligned ? "sm:flex sm:h-[clamp(16rem,32vw,34rem)] sm:items-center sm:justify-center sm:[&_picture]:contents" : ""}`}><ResponsiveProjectImage src={`${assetRoot}/${media.src}`} alt={media.alt} width={media.width} height={media.height} priority={priority} sizes={compact ? "(max-width: 639px) 208px, 32vw" : "(max-width: 767px) 100vw, 1280px"} className={aligned ? "h-auto w-full sm:max-h-full sm:object-contain" : "h-auto w-full"} /></div><figcaption className="mt-3 text-xs leading-5 text-workspace-muted">{media.caption}</figcaption></figure>;
}

function MediaPair({ media }: { media: readonly PortfolioMedia[] }) {
  const includesPortraitEvidence = media.some((item) => item.height > item.width);
  return <div className={`grid gap-6 sm:items-start ${includesPortraitEvidence ? "sm:grid-cols-[minmax(0,1.65fr)_minmax(9rem,0.55fr)]" : "lg:grid-cols-2"}`}>{media.map((item) => <Figure key={item.src} media={item} compact={item.height > item.width} aligned />)}</div>;
}

function EvidenceBlock({ title, text, note, media, after = false }: { title: string; text: string; note?: string; media: readonly PortfolioMedia[]; after?: boolean }) {
  return <div className={`space-y-7 sm:space-y-9 ${after ? "rounded-2xl bg-[#dcefff] p-5 sm:p-8" : ""}`}><div className="max-w-4xl space-y-4"><h3 className="case-study-subsection-title text-neutral-800">{title}</h3><p className="text-base leading-8 text-neutral-600">{text}</p>{note ? <p className="text-sm leading-7 text-neutral-500">{note}</p> : null}</div><MediaPair media={media} /></div>;
}

function OutcomeRows({ project }: { project: PortfolioProject }) {
  return <div className="overflow-hidden rounded-2xl bg-[#0e1820] text-white">{project.hero.outputs.map((output) => <div key={output.label} className="grid gap-2 border-b border-white/10 px-5 py-5 last:border-b-0 sm:grid-cols-[8rem_1fr] sm:gap-8 sm:px-7"><span className="font-mono text-xs font-bold text-[#78c8ff]">{output.label}</span><p className="text-sm leading-6 text-slate-100 sm:text-base">{output.value}</p></div>)}</div>;
}

function FlowComparison({ project }: { project: PortfolioProject }) {
  return <div className="grid gap-5 lg:grid-cols-2">{project.actTwo.diffSync.flows.map((flow, index) => <article key={flow.name} className={`rounded-2xl p-6 sm:p-8 ${index === 0 ? "bg-[#e7e3dc]" : "bg-[#2e94e3] text-white"}`}><div className={`flex flex-wrap items-start justify-between gap-4 ${index === 0 ? "line-through decoration-neutral-500 decoration-2" : ""}`}><h4 className={`text-lg font-bold ${index === 0 ? "text-neutral-800" : "text-white"}`}>{flow.name}</h4><span className={`rounded-full px-3 py-1 text-xs font-semibold ${index === 0 ? "bg-white text-neutral-600" : "bg-white/15 text-white"}`}>{flow.status}</span></div><ol className={`mt-8 space-y-3 ${index === 0 ? "line-through decoration-neutral-500 decoration-2" : ""}`}>{flow.steps.map((step, stepIndex) => <li key={step} className="grid grid-cols-[2rem_1fr] items-center gap-3"><span className={`flex h-8 w-8 items-center justify-center rounded-full text-xs font-bold ${index === 0 ? "bg-white text-neutral-700" : "bg-white text-[#12689f]"}`}>{index === 1 && stepIndex === flow.steps.length - 1 ? <Check className="h-4 w-4" aria-hidden="true" /> : stepIndex + 1}</span><span className={`text-sm font-medium ${index === 0 ? "text-neutral-700" : "text-white"}`}>{step}</span></li>)}</ol></article>)}</div>;
}

function OperatingSystemMap({ tree, locale }: { tree: MindmapNode; locale: Locale }) {
  return <div className="rounded-2xl bg-[#dcefff] p-5 sm:p-8" aria-label={labels[locale].systemMap}><h3 className="text-center text-2xl font-bold tracking-[-0.02em] text-[#0e1820]">{displayNodeLabel(tree.label, locale)}</h3><div className="mt-7 grid gap-4 lg:grid-cols-3">{tree.children.map((layer, index) => <article key={layer.label} className={`rounded-2xl p-5 sm:p-6 ${index === 0 ? "bg-[#2e94e3] text-white" : index === 1 ? "bg-white text-[#0e1820]" : "bg-[#0e1820] text-white"}`}><h4 className="text-lg font-bold">{displayNodeLabel(layer.label, locale)}</h4><ul className="mt-5 space-y-2">{layer.children.map((item) => <li key={item.label} className={`rounded-xl px-3 py-2 text-sm ${index === 1 ? "bg-[#edf7ff] text-[#27465d]" : "bg-white/12 text-white"}`}>{displayNodeLabel(item.label, locale)}</li>)}</ul></article>)}</div></div>;
}

function Results({ project, locale }: { project: PortfolioProject; locale: Locale }) {
  return <div className="space-y-10"><div className="overflow-hidden rounded-2xl bg-white text-neutral-800" aria-label={labels[locale].results}>{project.actThree.results.rows.map((row) => { const unresolved = /unresolved|Qualified|未解决|有限定/.test(row.status); return <div key={row.area} className="grid gap-3 border-b border-neutral-100 p-5 last:border-b-0 sm:grid-cols-[7rem_1fr_11rem] sm:items-center sm:gap-6 sm:p-6"><strong className="text-sm">{row.area}</strong><p className="text-sm leading-6 text-neutral-600">{row.outcome}</p><span className={`inline-flex w-fit items-center gap-2 rounded-full px-3 py-1.5 text-xs font-semibold ${unresolved ? "bg-amber-50 text-amber-800" : "bg-emerald-50 text-emerald-800"}`}>{unresolved ? <CircleAlert className="h-3.5 w-3.5" aria-hidden="true" /> : <Check className="h-3.5 w-3.5" aria-hidden="true" />}{row.status}</span></div>; })}</div><div className="grid gap-6 lg:grid-cols-[0.55fr_1.45fr]"><h3 className="case-study-subsection-title !text-white">{labels[locale].open}</h3><ul className="space-y-3">{project.actThree.results.openQuestions.map((question) => <li key={question} className="flex gap-3 text-sm leading-6 text-slate-200 sm:text-base"><CircleAlert className="mt-1 h-4 w-4 shrink-0 text-[#78c8ff]" aria-hidden="true" /><span>{question}</span></li>)}</ul></div></div>;
}

export default function PortfolioOperatingSystemCaseStudyPage({ project, locale }: { project: PortfolioProject; locale: Locale }) {
  const dictionary = getDictionary(locale); const localLabels = labels[locale];
  void (locale === "zh" ? zhBalance : enBalance); void (locale === "zh" ? zhCoverage : enCoverage);
  return <main className="case-study-page min-h-screen bg-workspace-bg text-workspace-text">
    <header className="sticky top-0 z-30 border-b border-workspace-border bg-workspace-bg/95 backdrop-blur-sm"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-3 sm:px-8"><Link href={locale === "zh" ? "/zh" : "/"} className="inline-flex min-h-11 items-center gap-2 rounded-lg px-3 font-mono text-xs font-bold hover:bg-white focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-workspace-accent"><ArrowLeft className="h-4 w-4" aria-hidden="true" />{dictionary.shared.workspace}</Link><nav className="hidden items-center gap-1 lg:flex" aria-label={dictionary.shared.caseStudy}>{localLabels.nav.map((label, index) => <Link key={label} href={`#act-${index + 1}`} className="rounded-lg px-3 py-2 text-xs font-semibold text-neutral-600 hover:bg-white hover:text-neutral-900 focus-visible:outline-2 focus-visible:outline-workspace-accent">{label}</Link>)}</nav><LanguageSwitcher locale={locale} label={dictionary.shared.languageName} /></div></header>
    <article>
      <SourceSection id="hero" sourceIds={project.hero.sourceIds} className="mx-auto max-w-7xl px-5 pb-24 pt-10 sm:px-8 sm:pb-32 sm:pt-16"><div className="overflow-hidden rounded-2xl bg-[#0e1820] text-white shadow-[0_34px_90px_-58px_rgba(14,24,32,0.82)]"><div className="space-y-9 px-6 py-9 sm:px-10 sm:py-12 lg:px-14"><h1 className="case-study-title !max-w-none !text-white">{project.title}</h1><dl className="grid gap-5 text-sm text-slate-200 sm:grid-cols-3 sm:gap-8"><div><dt className="font-mono text-xs font-bold text-[#78c8ff]">{localLabels.role}</dt><dd className="mt-1 leading-6">{project.meta.role}</dd></div><div><dt className="font-mono text-xs font-bold text-[#78c8ff]">{localLabels.duration}</dt><dd className="mt-1 leading-6">{project.meta.duration}</dd></div><div><dt className="font-mono text-xs font-bold text-[#78c8ff]">{localLabels.type}</dt><dd className="mt-1 leading-6">{project.meta.type}</dd></div></dl></div><div className="bg-[#dcefff] p-3 sm:p-5"><Figure media={project.hero.media} priority /></div></div><div className="mt-10 grid gap-9 lg:grid-cols-[1.05fr_0.95fr] lg:items-start lg:gap-14"><div className="space-y-5"><p className="text-base leading-8 text-neutral-600 sm:text-lg">{project.hero.summary}</p><p className="text-sm leading-7 text-neutral-500">{project.hero.tools}</p><p className="rounded-xl bg-[#eeeae3] p-4 text-sm leading-6 text-neutral-600"><strong>{localLabels.boundary}: </strong>{project.hero.boundary}</p></div><OutcomeRows project={project} /></div></SourceSection>
      <SourceSection id="act-1" sourceIds={project.actOne.sourceIds} className="bg-white py-24 sm:py-32"><div className="mx-auto max-w-7xl space-y-20 px-5 sm:px-8 sm:space-y-28"><SectionHeading title={project.actOne.title} summary={project.actOne.summary} protectedPhrase={locale === "zh" ? "AI 生成了" : undefined} /><EvidenceBlock {...project.actOne.draft} /><EvidenceBlock {...project.actOne.critique} /><EvidenceBlock {...project.actOne.refined} after /><EvidenceBlock {...project.actOne.windows} after /></div></SourceSection>
      <SourceSection id="act-2" sourceIds={project.actTwo.sourceIds} className="mx-auto max-w-7xl space-y-20 px-5 py-24 sm:space-y-28 sm:px-8 sm:py-32"><SectionHeading title={project.actTwo.title} summary={project.actTwo.summary} /><div className="space-y-8"><div className="max-w-4xl space-y-4"><h3 className="case-study-subsection-title">{project.actTwo.diffSync.title}</h3><p className="text-base leading-8 text-neutral-600">{project.actTwo.diffSync.text}</p><p className="rounded-2xl bg-[#dcefff] p-6 text-base font-medium leading-8 text-[#18384f]"><strong>{localLabels.decision}: </strong>{project.actTwo.diffSync.decision}</p></div><FlowComparison project={project} /><p className="text-sm leading-6 text-neutral-500"><strong>{localLabels.boundary}: </strong>{project.actTwo.diffSync.boundary}</p></div><div className="space-y-8"><div className="max-w-4xl space-y-4"><h3 className="case-study-subsection-title">{project.actTwo.contentModel.title}</h3><p className="text-base leading-8 text-neutral-600">{project.actTwo.contentModel.text}</p><p className="text-base font-medium leading-8 text-neutral-800"><strong>{localLabels.decision}: </strong>{project.actTwo.contentModel.decision}</p></div><Figure media={project.actTwo.contentModel.media} /></div><div className="grid gap-4 rounded-2xl bg-[#e9f4fb] p-4 lg:grid-cols-2"><article className="rounded-2xl bg-[#e9f4fb] p-6 sm:p-8"><h3 className="case-study-subsection-title">{project.actTwo.product.title}</h3><p className="mt-4 text-sm leading-7 text-neutral-600 sm:text-base">{project.actTwo.product.text}</p></article><div className="space-y-4"><p className="rounded-2xl bg-[#e9f4fb] p-6 text-sm leading-7 text-neutral-600 sm:p-8">{project.actTwo.product.versioning}</p><p className="rounded-2xl bg-[#e9f4fb] p-6 text-sm leading-7 text-neutral-600 sm:p-8">{project.actTwo.product.deployment}</p></div></div></SourceSection>
      <SourceSection id="act-3" sourceIds={project.actThree.sourceIds} className="bg-[#0e1820] py-24 text-white sm:py-32"><div className="mx-auto max-w-7xl space-y-20 px-5 sm:space-y-28 sm:px-8"><SectionHeading title={project.actThree.title} summary={project.actThree.summary} inverse /><div className="space-y-8"><div className="max-w-4xl space-y-4"><h3 className="case-study-subsection-title !text-white">{project.actThree.operatingSystem.title}</h3><p className="text-base leading-8 text-slate-200">{project.actThree.operatingSystem.text}</p></div>{project.actThree.operatingSystem.mindmap ? <OperatingSystemMap tree={project.actThree.operatingSystem.mindmap} locale={locale} /> : null}<p className="text-sm leading-6 text-slate-300"><strong>{localLabels.boundary}: </strong>{project.actThree.operatingSystem.boundary}</p></div><div className="space-y-10"><SectionHeading title={project.actThree.results.title} summary={project.actThree.results.summary} inverse /><Results project={project} locale={locale} /></div></div></SourceSection>
    </article>
  </main>;
}
